### ISSUE TITLE
Fonts to port

### ISSUE THREAD

**Issue by xTibor** [xTibor/serenity-fontdev#1]
* [x] Commodore 128
* [x] ZX Spectrum
* [x] IBM CGA
* [x] IBM VGA
* [x] Envy Code A (https://damieng.com/typography/envy-code-a)
* [x] Envy Code B (https://damieng.com/typography/envy-code-b)
* [x] Apple Macintosh (Chicago)
* [x] Apple II
* [x] https://www.spriters-resource.com/ds_dsi/newsupermariobros/sheet/120201/
* [x] FastTracker II
* [x] Courier
* [ ] https://int10h.org/oldschool-pc-fonts/fontlist/
* [ ] ZX Origins (https://damieng.com/blog/2019/06/03/zxorigins-free-8-bit-fonts-for-games)
* [ ] Impulse Tracker

**Comment by damieng** [comment]
Hi there. A redistribution of ZX Origins fonts into your repo would be against the license.

**Comment by xTibor** [comment]
Deleted the repository to be sure I'm not infringing on anything.
